export enum TextVariants {
  display0 = 'display0',
  display1 = 'display1',
  display2 = 'display2',
  display3 = 'display3',
  display4 = 'display4',
  heading1 = 'heading1',
  heading2 = 'heading2',
  heading3 = 'heading3',
  heading4 = 'heading4',
  body1 = 'body1',
  body2 = 'body2',
  body3 = 'body3',
  labelButton = 'labelButton',
  labelCtaLg = 'labelCtaLg',
  labelCtaSm = 'labelCtaSm',
  labelEmail = 'labelEmail',
  labelText = 'labelText',
  labelTextBadge = 'labelTextBadge',
}
