export enum TextVariants {
  blockquote = 'blockquote',
  heading1 = 'heading1',
  heading2 = 'heading2',
  heading3 = 'heading3',
  heading4 = 'heading4',
  heading5 = 'heading5',
  title1 = 'title1',
  title2 = 'title2',
  title3 = 'title3',
  title4 = 'title4',
  body1 = 'body1',
  body2 = 'body2',
  body3 = 'body3',
  string1 = 'string1',
  string2 = 'string2',
  string3 = 'string3',
  button = 'button',
  email = 'email',
  label = 'label',
  link = 'link',
  badge = 'badge',
  snwFlyoutLink = 'snwFlyoutLink',
  snwHeaderLink = 'snwHeaderLink',
  snwHeadingHero1 = 'snwHeadingHero1',
  snwHeadingHero2 = 'snwHeadingHero2',

  // New variants
  displayMedium = 'displayMedium',
  displaySmall = 'displaySmall',
  headingLarge = 'headingLarge',
  headingMedium = 'headingMedium',
  headingSmall = 'headingSmall',
  headingM = 'headingM',
  headingS = 'headingS',
  bodyL = 'bodyL',
  bodyM = 'bodyM',
  bodyS = 'bodyS',
  linkStylised = 'linkStylised',
  linkL = 'linkL',
  linkM = 'linkM',
}

export enum TextAlignments {
  left = 'left',
  center = 'center',
  right = 'right',
}
