export enum TextVariants {
  blockquote = 'blockquote',
  heading1 = 'heading1',
  heading2 = 'heading2',
  heading3 = 'heading3',
  heading3Italic = 'heading3Italic',
  heading4 = 'heading4',
  heading4Italic = 'heading4Italic',
  heading5 = 'heading5',

  // Eyebrow variants
  eyebrowLg = 'eyebrowLg',
  eyebrowSm = 'eyebrowSm',

  title1 = 'title1',
  title2 = 'title2',
  title3 = 'title3',
  title4 = 'title4',
  bodyLg = 'bodyLg',
  bodyLgBold = 'bodyLgBold',
  bodyMd = 'bodyMd',
  bodyMdBold = 'bodyMdBold',
  bodySm = 'bodySm',
  bodySmBold = 'bodySmBold',
  body1 = 'body1',
  body2 = 'body2',
  body3 = 'body3',
  string1 = 'string1',
  string2 = 'string2',
  string3 = 'string3',

  labelLg = 'labelLg',
  labelLgBold = 'labelLgBold',
  labelMd = 'labelMd',
  labelMdBold = 'labelMdBold',
  labelSm = 'labelSm',
  labelSmBold = 'labelSmBold',
  button = 'button',
  email = 'email',
  label = 'label',
  link = 'link',
  linkBold = 'linkBold',
  badge = 'badge',
  snwFlyoutLink = 'snwFlyoutLink',
  snwHeaderLink = 'snwHeaderLink',
  snwHeadingHero1 = 'snwHeadingHero1',
  snwHeadingHero2 = 'snwHeadingHero2',
}

export enum TextAlignments {
  left = 'left',
  center = 'center',
  right = 'right',
}
