import Link from './Link';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Link,
  'https://www.figma.com/file/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?type=design&node-id=5149-57723&mode=design&t=IEWcXe8zmi5I3z5B-4',
  {
    props: {
      ctaLabelContent: figma.string('CTA Label Content'),
      breakpoint: figma.enum('Breakpoint', {
        Default: 'default',
        'BP-1': 'bp-1',
        'BP-4': 'bp-4',
      }),
      state: figma.enum('State', {
        Static: 'static',
        Hover: 'hover',
      }),
    },
    example: ({ ctaLabelContent, ...props }) => (
      <Link {...props} href="www.cnn.com">
        {ctaLabelContent}
      </Link>
    ),
  },
);
