name: 'Validate PR Title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          subjectPattern: ^[A-Z0-9]+-[0-9]+ .*$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            needs to start with the Jira ticket number. For instance "L3-2149 My awesome feature"
